FROM arm64v8/python:3.7-bullseye

WORKDIR /app

RUN apt-get update && \
    apt install -y cmake
COPY requirements.txt ./
RUN pip install -r requirements.txt


COPY . .

CMD [ "python3", "-u", "./main.py" ]